import os
import pkgutil

SRC = os.path.join(os.path.dirname(__file__), "../src")
SKIP_DIRS = {"__pycache__"}
SKIP_SUFFIXES = (".egg-info",)


def should_skip_dir(path):
    name = os.path.basename(path)
    return name in SKIP_DIRS or name.endswith(SKIP_SUFFIXES) or name.startswith(".")


def ensure_init(path):
    init_f = os.path.join(path, "__init__.py")
    # 1) create blank if missing
    if not os.path.exists(init_f):
        open(init_f, "w").close()

    # 2) discover modules and write imports
    names = sorted(
        name
        for _, name, _ in pkgutil.iter_modules([path])
        if name not in SKIP_DIRS and not name.endswith(SKIP_SUFFIXES) and not name.startswith(".")
    )
    lines = [f"from .{n} import *" for n in names]
    with open(init_f, "w", encoding="utf-8") as f:
        f.write("# auto-generated by gen_inits.py\n")
        if lines:
            f.write("\n".join(lines) + "\n")


def main():
    for root, dirs, files in os.walk(os.path.normpath(SRC)):
        dirs[:] = [d for d in dirs if not should_skip_dir(os.path.join(root, d))]
        if should_skip_dir(root):
            continue
        ensure_init(root)


if __name__ == "__main__":
    main()
